// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awgndvcyeyhilysbpkem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z25kdmN5ZXloaWx5c2Jwa2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjQ2ODksImV4cCI6MjA1OTM0MDY4OX0.-bWnZEY1OKrOMEAnFjEznSdAJPzkHiKA4s2LbZsKE8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);